### PR TITLE
Add executions.get_root action

### PR DESCRIPTION
**Pull request by shusugmt**

### CODE REVIEW

**Comment by m4dcoder** [comment]
Does it make sense to add unit tests here?

**Comment by shusugmt** [comment]
It should be, but I don't know if there is any pack that is doing such test off the top of my head. 
@LindsayHill Any thoughts?

**Comment by LindsayHill** [comment]
There's quite a few packs with unit tests - e.g. [vSphere](https://github.com/StackStorm-Exchange/stackstorm-vsphere/tree/master/tests), [manageIQ](https://github.com/StackStorm-Exchange/stackstorm-manageiq/tree/master/tests)

**Review by warrenvw — APPROVED** [review]
Looks good to me! 👍

**Pull request merged**
